<a href="https://colab.research.google.com/github/Sriram192/Python_Practice/blob/master/Python_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This notebook is based on the youtube course "Python Pandas For Your Grandpa". Link to the video course: 

<https://www.youtube.com/playlist?list=PL9oKUrtC4VP7ry0um1QOUUfJBXKnkf-dA>

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Series in Pandas:
Series is very much similar to a numpy 1D array. Except in Pandas its has much more functionality

In [4]:
# Series in Pandas
x = pd.Series([1,2,4,6,7,8,5])
print(x)
#Note that the index of each element in inbuilt into the series. 3
#Also the output include the the datatyoe of the series which is int64 in this case

0    1
1    2
2    4
3    6
4    7
5    8
6    5
dtype: int64


In [7]:
y = pd.Series(['name','age','blood_group','sex'])
print(y)

0           name
1            age
2    blood_group
3            sex
dtype: object


In [8]:
x.to_numpy() #convert to numpy 1D array

array([1, 2, 4, 6, 7, 8, 5])

In [9]:
x.head() #prints the first five elements

0    1
1    2
2    4
3    6
4    7
dtype: int64

In [10]:
x.tail() #prints the last five elements

2    4
3    6
4    7
5    8
6    5
dtype: int64

In [12]:
#Making a series from a python dictionary:
d = {'a':1,'b':5,'c':6,'d':8}
d = pd.Series(d)
print(d)

a    1
b    5
c    6
d    8
dtype: int64


TypeError: ignored

In [16]:
#making series froma list
a = [1,2,6,7,4,6,7]
a = pd.Series(a)
print(a)

0    1
1    2
2    6
3    7
4    4
5    6
6    7
dtype: int64


In [17]:
#converting a numpy array to a series:
n = np.array([10.,40,20,30])
print(n)
n = pd.Series(n)
print(n)

[10. 40. 20. 30.]
0    10.0
1    40.0
2    20.0
3    30.0
dtype: float64


In [19]:
pd.Series(np.linspace(start = 1,stop = 2,num = 10))

0    1.000000
1    1.111111
2    1.222222
3    1.333333
4    1.444444
5    1.555556
6    1.666667
7    1.777778
8    1.888889
9    2.000000
dtype: float64

In [25]:
pd.Series(np.random.normal(size=4))

0   -0.497091
1    0.236971
2    0.799660
3    0.631873
dtype: float64

# Accessing items from the series

In [30]:
x = pd.Series([9.,4,2,6,4,0,5,1])
x.index = [8,7,6,5,4,3,2,1]
print(x)

8    9.0
7    4.0
6    2.0
5    6.0
4    4.0
3    0.0
2    5.0
1    1.0
dtype: float64


In [31]:
x[3] #accesses the element with index 3  and not the third element

0.0

In [34]:
x.iloc[0]# this is the proper way to accecc the elements of the series. This accesses the zeroth element of the series

9.0

In [35]:
x.iloc[-1]#returns the last element of the series.

1.0

In [36]:
x.iloc[-3]#returns the third last element of the series

0.0

In [38]:
grades = pd.Series([45,67,35,78,25,89])
grades.index = ['Ram','Krupa','Jai','Buvana','Raksha','Appa']
print(grades)

Ram       45
Krupa     67
Jai       35
Buvana    78
Raksha    25
Appa      89
dtype: int64


In [39]:
grades['Krupa']

67

#Basic Operation with pd.Series

In [40]:
A = pd.Series([10,20,30,40,50])
B = pd.Series([1,2,3,4,5])
C = A + B #adds elements with the same index rather than addition by position
print(C)

0    11
1    22
2    33
3    44
4    55
dtype: int64


In [41]:
a = pd.Series([1,2,3,4])
b = pd.Series([10,20])
c = a + b
print(c)

0    11.0
1    22.0
2     NaN
3     NaN
dtype: float64


In [43]:
# the '+' operation only adds the elements with the same index for example:
A = pd.Series([10,20,30,40,50],index = [4,3,2,1,0]) #index reversed
print(A)
B = pd.Series([1,2,3,4,5])
C = A + B #adds elements with the same index rather than addition by position
print(C)

4    10
3    20
2    30
1    40
0    50
dtype: int64
0    51
1    42
2    33
3    24
4    15
dtype: int64


In [45]:
 # For cases where we want an addition of these Series by position,we use 'to_numpy()'
 C = A.to_numpy() + B.to_numpy()
 print(C)

[11 22 33 44 55]


In [46]:
print(A + B.to_numpy())#adds the elements by position but the index of A is retained

4    11
3    22
2    33
1    44
0    55
dtype: int64


# Boolean indexing

In [47]:
foo = pd.Series([1,3,2,5,3,6,2,7])
foo < 3 #shows us a series with boolean values for each element

0     True
1    False
2     True
3    False
4    False
5    False
6     True
7    False
dtype: bool

In [48]:
mask = foo < 3 #saving the boolean series in a variable
print(mask)

0     True
1    False
2     True
3    False
4    False
5    False
6     True
7    False
dtype: bool


In [49]:
foo[mask]#prints out the elements that match the condition

0    1
2    2
6    2
dtype: int64

In [50]:
foo[foo<3]#the same can be written in a single line

0    1
2    2
6    2
dtype: int64